version: '3.8' 
 
services:
  Rabbito:
    image: rabbitmq:management
    hostname: "rabbitmq-dev"
    ports: 
      - "15672:15672"
      - "5672:5672"
    networks:
      - network1

  planning: 
    image: williamkruse/taxaplanning:latest 
    environment: 
      - CSVPath=//srv/images/test.csv
      - CSVPath2=//srv/images
      - RHQHN=rabbitmq-dev
    restart: unless-stopped
    ports:
          - "5001:80" 
    networks: 
      - network1
    volumes: 
      - images:/srv/images
 
  booking: 
    image: williamkruse/taxabooking:latest 
    environment: 
      - CSVPath=//srv/images/test.csv
      - RHQHN=rabbitmq-dev
    ports: 
      - "5002:80" 
    networks: 
      - network1
    volumes: 
      - images:/srv/images
  maintain: 
    image: williamkruse/maintain:latest 
    environment: 
      - CSVPath=//srv/images/
      - RHQHN=rabbitmq-dev
    ports: 
      - "5009:80" 
    networks: 
      - network1
    volumes: 
      - images:/srv/images
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - network1
  grafana:
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - network1
 
volumes: 
  images: 
    external: false
  grafana-storage: 
    external: false 
 
networks: 
  network1: